import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import FloatingMessenger from '@/components/FloatingMessenger';
import Navbar from '@/components/Navbar';
import './globals.css';
import { Providers } from './providers';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'SoundBook',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Providers>
          <Navbar />
          {children}
          <FloatingMessenger />
        </Providers>
      </body>
    </html>
  );
}
